version: '3'
services:
  product-service:
    container_name: product-api
    build: .
    depends_on:
      - product-postgres
    ports: 
      - 50052:50052
    restart: on-failure
    volumes:
      - ./:/usr/src/app-product/
    networks:
      - fullstack

  product-postgres:
    image: postgres:latest
    container_name: product_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5436:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

networks:
  fullstack:
    external: true

volumes:
  database_postgres:

